""" UpBack constants """

UPBACK_EXCLUDE_FILE = ".upback.exclude"
UPBACK_CONF_FILE = ".upback.config"
UPBACK_REMOTE_BACKUP = ".upback.remote"
UPBACK_CONFLICTS_FILE = "UPBACK_CONFLICTS"
NOOP = 0
COPY_A_TO_B = 1
COPY_B_TO_A = 2
DELETE_FROM_A = 3
DELETE_FROM_B = 4
CONFLICT = 5

OPERATION_COPY_A_TO_B = 1
OPERATION_COPY_B_TO_A = 2
OPERATION_DELETE_FROM_A = 3
OPERATION_DELETE_FROM_B = 4
OPERATION_CONFLICT = 5

CHANGE_NONE = 1
CHANGE_DELETED = 2
CHANGE_NEW = 3
CHANGE_SAME = 4
CHANGE_UPDATED = 5

BACKUP_SUFFIX_DEFAULT = "%Y%m%d_%H%M%S"

STATUS_OK = 0
STATUS_ERROR = 1
STATUS_INTERRUPTED = 9
